# Generated by Django 5.0.6 on 2024-07-04 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimage',
            name='Image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
